global:
  postgresql:
    auth:
      postgresPassword: "pass"  
      username: "user"
      password: "pass"         
      database: "tinkoff_db"
      replicationPassword: "replpass"  

architecture: replication
postgresql:
  replicaCount: 2  
  synchronousCommit: "on"
  synchronousReplication: true
  numSynchronousReplicas: 1  
  
  
  primary:
    persistence:
      enabled: true  
      size: 10Gi
      storageClass: ""  
    
    
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:  
        memory: 2Gi
        cpu: 1
  
  
  readReplicas:
    persistence:
      enabled: true  
      size: 10Gi
      storageClass: ""
    
    
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: 1

