apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend  
  labels:
    app: backend  
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: backend  
  template:  
    metadata:
      labels:
        app: backend  
    spec:
      containers:
      - name: backend
        image: stayfatal/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"    
            memory: "128Mi" 
          limits:
            cpu: "500m"    
            memory: "512Mi" 