name: Build, Push & Deploy

on:
  push:
    branches: [cluster-tgBotDeploy]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout кода
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Логин в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # 3. Сборка и пуш образа
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            stayfatal/backend:latest

      # 4. Установка ZeroTier
      - name: Install ZeroTier
        run: |
          curl -s https://install.zerotier.com | sudo bash
          sudo zerotier-cli join ${{ secrets.ZEROTIER_NETWORK_ID }}
      
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass
      
      # 5. Подключение по SSH и деплой
      - name: Deploy via SSH
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@10.147.19.70 "
          kubectl rollout restart deployment backend "